import { LeapMonthOp, NativeCalendar, NativeConvertOps, NativeDateModOps, NativeDateRefineOps, NativeDayOfYearOps, NativeDaysInMonthOps, NativeDaysInYearOps, NativeDiffOps, NativeInLeapYearOps, NativeMonthDayModOps, NativeMonthDayParseOps, NativeMonthDayRefineOps, NativeMonthsInYearOps, NativeMoveOps, NativePartOps, NativeStandardOps, NativeWeekOps, NativeYearMonthDiffOps, NativeYearMonthModOps, NativeYearMonthMoveOps, NativeYearMonthRefineOps } from './calendarNative.ts';
import { DayOps, DiffOps, MoveOps } from './calendarOps.ts';
export declare const isoYearMonthRefineOps: NativeYearMonthRefineOps;
export declare const isoDateRefineOps: NativeDateRefineOps;
export declare const isoMonthDayRefineOps: NativeMonthDayRefineOps;
export declare const isoYearMonthModOps: NativeYearMonthModOps;
export declare const isoDateModOps: NativeDateModOps;
export declare const isoMonthDayModOps: NativeMonthDayModOps;
export declare const isoMoveOps: NativeMoveOps;
export declare const isoDiffOps: NativeDiffOps;
export declare const isoDayOps: DayOps;
export declare const isoYearMonthMoveOps: NativeYearMonthMoveOps;
export declare const isoYearMonthDiffOps: NativeYearMonthDiffOps;
export declare const isoPartOps: NativePartOps;
export declare const isoInLeapYearOps: NativeInLeapYearOps;
export declare const isoMonthsInYearOps: NativeMonthsInYearOps;
export declare const isoDaysInMonthOps: NativeDaysInMonthOps;
export declare const isoDaysInYearOps: NativeDaysInYearOps;
export declare const isoDayOfYearOps: NativeDayOfYearOps;
export declare const isoWeekOps: NativeWeekOps;
export declare const isoMonthDayParseOps: NativeMonthDayParseOps;
export declare const isoStandardOps: NativeStandardOps;
export declare const intlYearMonthRefineOps: Omit<NativeYearMonthRefineOps, 'id'>;
export declare const intlDateRefineOps: Omit<NativeDateRefineOps, 'id'>;
export declare const intlMonthDayRefineOps: Omit<NativeMonthDayRefineOps, 'id'>;
export declare const intlYearMonthModOps: Omit<NativeYearMonthModOps, 'id'>;
export declare const intlDateModOps: Omit<NativeDateModOps, 'id'>;
export declare const intlMonthDayModOps: Omit<NativeMonthDayModOps, 'id'>;
export declare const intlMoveOps: NativeMoveOps;
export declare const intlDiffOps: NativeDiffOps;
export declare const intlDayOps: DayOps;
export declare const intlYearMonthMoveOps: NativeYearMonthMoveOps;
export declare const intlYearMonthDiffOps: NativeYearMonthDiffOps;
export declare const intlPartOps: NativePartOps;
export declare const intlInLeapYearOps: NativeInLeapYearOps;
export declare const intlMonthsInYearOps: NativeMonthsInYearOps;
export declare const intlDaysInMonthOps: NativeDaysInMonthOps;
export declare const intlDaysInYearOps: NativeDaysInYearOps;
export declare const intlDayOfYearOps: NativeDayOfYearOps;
export declare const intlWeekOps: NativeWeekOps;
export declare const intlMonthDayParseOps: NativeMonthDayParseOps;
export declare const intlStandardOps: Omit<NativeStandardOps, 'id'>;
export declare const createNativeYearMonthRefineOps: (calendarId: string) => Omit<NativeYearMonthRefineOps, "id"> & NativeCalendar;
export declare const createNativeDateRefineOps: (calendarId: string) => Omit<NativeDateRefineOps, "id"> & NativeCalendar;
export declare const createNativeMonthDayRefineOps: (calendarId: string) => Omit<NativeMonthDayRefineOps, "id"> & NativeCalendar;
export declare const createNativeYearMonthModOps: (calendarId: string) => Omit<NativeYearMonthModOps, "id"> & NativeCalendar;
export declare const createNativeDateModOps: (calendarId: string) => Omit<NativeDateModOps, "id"> & NativeCalendar;
export declare const createNativeMonthDayModOps: (calendarId: string) => Omit<NativeMonthDayModOps, "id"> & NativeCalendar;
export declare const createNativeConvertOps: (calendarId: string) => NativeConvertOps & NativeCalendar;
export declare const createNativeMoveOps: (calendarId: string) => MoveOps & NativeConvertOps & {
    monthCodeParts: import("./calendarNative.ts").MonthCodePartsOp;
    monthsInYearPart: import("./calendarNative.ts").MonthsInYearPartOp;
    daysInMonthParts: import("./calendarNative.ts").DaysInMonthPartsOp;
    leapMonth: LeapMonthOp;
} & NativeCalendar;
export declare const createNativeDiffOps: (calendarId: string) => DiffOps & NativeConvertOps & {
    monthCodeParts: import("./calendarNative.ts").MonthCodePartsOp;
    monthsInYearPart: import("./calendarNative.ts").MonthsInYearPartOp;
    daysInMonthParts: import("./calendarNative.ts").DaysInMonthPartsOp;
    leapMonth: LeapMonthOp;
} & {
    monthsInYearSpan: import("./calendarNative.ts").MonthsInYearSpanOp;
} & NativeCalendar;
export declare const createNativeDayOps: (calendarId: string) => DayOps & NativeCalendar;
export declare const createNativeYearMonthMoveOps: (calendarId: string) => MoveOps & NativeConvertOps & {
    monthCodeParts: import("./calendarNative.ts").MonthCodePartsOp;
    monthsInYearPart: import("./calendarNative.ts").MonthsInYearPartOp;
    daysInMonthParts: import("./calendarNative.ts").DaysInMonthPartsOp;
    leapMonth: LeapMonthOp;
} & DayOps & NativeCalendar;
export declare const createNativeYearMonthDiffOps: (calendarId: string) => DiffOps & NativeConvertOps & {
    monthCodeParts: import("./calendarNative.ts").MonthCodePartsOp;
    monthsInYearPart: import("./calendarNative.ts").MonthsInYearPartOp;
    daysInMonthParts: import("./calendarNative.ts").DaysInMonthPartsOp;
    leapMonth: LeapMonthOp;
} & {
    monthsInYearSpan: import("./calendarNative.ts").MonthsInYearSpanOp;
} & DayOps & NativeCalendar;
export declare const createNativePartOps: (calendarId: string) => NativePartOps & NativeCalendar;
export declare const createNativeInLeapYearOps: (calendarId: string) => NativeInLeapYearOps & NativeCalendar;
export declare const createNativeMonthsInYearOps: (calendarId: string) => NativeMonthsInYearOps & NativeCalendar;
export declare const createNativeDaysInMonthOps: (calendarId: string) => NativeDaysInMonthOps & NativeCalendar;
export declare const createNativeDaysInYearOps: (calendarId: string) => NativeDaysInYearOps & NativeCalendar;
export declare const createNativeDayOfYearOps: (calendarId: string) => NativeDayOfYearOps & NativeCalendar;
export declare const createNativeWeekOps: (calendarId: string) => NativeWeekOps & NativeCalendar;
export declare const createNativeMonthDayParseOps: (calendarId: string) => NativeMonthDayParseOps & NativeCalendar;
export declare const createNativeStandardOps: (calendarId: string) => Omit<NativeStandardOps, "id"> & NativeCalendar;
