import { Callable } from './utils.ts';
export declare function requireStringOrUndefined(input: string | undefined): string | undefined;
export declare function requirePositiveIntegerOrUndefined(input: number | undefined): number | undefined;
export declare function requireIntegerOrUndefined(input: number | undefined): number | undefined;
export declare function requirePositiveInteger(arg: number): number;
export declare function requireInteger(arg: number): number;
export declare function requireNonNullish<T>(o: T): T;
export declare function requirePropDefined<V>(optionName: string, optionVal: V | null | undefined): V;
export declare function requireObjectLike<O extends {}>(arg: O): O;
export declare const requireString: (arg: string, entityName?: string) => string;
export declare const requireBoolean: (arg: boolean, entityName?: string) => boolean;
export declare const requireNumber: (arg: number, entityName?: string) => number;
export declare const requireFunction: (arg: Callable, entityName?: string) => Callable;
export declare function requireNumberIsInteger(num: number, entityName?: string): number;
export declare function toString(arg: string): string;
export declare function toStringViaPrimitive(arg: string, entityName?: string): string;
export declare function toBigInt(bi: bigint): bigint;
export declare function toNumber(arg: number, entityName?: string): number;
export declare function toInteger(arg: number, entityName?: string): number;
export declare function toStrictInteger(arg: number, entityName?: string): number;
export declare function toPositiveInteger(arg: number, entityName?: string): number;
