import { MoveOps } from './calendarOps.ts';
import { IsoDateFields, IsoDateTimeFields, IsoTimeFields } from './isoFields.ts';
import { RelativeToSlots } from './markerSystem.ts';
import { RelativeToOptions } from './optionsRefine.ts';
import { DurationSlots, InstantSlots, PlainDateSlots, PlainDateTimeSlots, PlainMonthDaySlots, PlainTimeSlots, PlainYearMonthSlots, ZonedDateTimeSlots } from './slots.ts';
import { TimeZoneOps } from './timeZoneOps.ts';
import { NumberSign } from './utils.ts';
export declare function compareInstants(instantSlots0: InstantSlots, instantSlots1: InstantSlots): NumberSign;
export declare function compareZonedDateTimes(zonedDateTimeSlots0: ZonedDateTimeSlots, zonedDateTimeSlots1: ZonedDateTimeSlots): NumberSign;
export declare function compareDurations<RA>(refineRelativeTo: (relativeToArg?: RA) => RelativeToSlots | undefined, getCalendarOps: (calendarId: string) => MoveOps, getTimeZoneOps: (timeZoneId: string) => TimeZoneOps, durationSlots0: DurationSlots, durationSlots1: DurationSlots, options?: RelativeToOptions<RA>): NumberSign;
export declare function compareIsoDateTimeFields(isoFields0: IsoDateTimeFields, isoFields1: IsoDateTimeFields): NumberSign;
export declare function compareIsoDateFields(isoFields0: IsoDateFields, isoFields1: IsoDateFields): NumberSign;
export declare function compareIsoTimeFields(isoFields0: IsoTimeFields, isoFields1: IsoTimeFields): NumberSign;
export declare function instantsEqual(instantSlots0: InstantSlots, instantSlots1: InstantSlots): boolean;
export declare function zonedDateTimesEqual(zonedDateTimeSlots0: ZonedDateTimeSlots, zonedDateTimeSlots1: ZonedDateTimeSlots): boolean;
export declare function plainDateTimesEqual(plainDateTimeSlots0: PlainDateTimeSlots, plainDateTimeSlots1: PlainDateTimeSlots): boolean;
export declare function plainDatesEqual(plainDateSlots0: PlainDateSlots, plainDateSlots1: PlainDateSlots): boolean;
export declare function plainYearMonthsEqual(plainYearMonthSlots0: PlainYearMonthSlots, plainYearMonthSlots1: PlainYearMonthSlots): boolean;
export declare function plainMonthDaysEqual(plainMonthDaySlots0: PlainMonthDaySlots, plainMonthDaySlots1: PlainMonthDaySlots): boolean;
export declare function plainTimesEqual(plainTimeSlots0: PlainTimeSlots, plainTimeSlots1: PlainTimeSlots): boolean;
export declare function isTimeZoneIdsEqual(a: string, b: string): number | boolean | undefined;
