import { NativeDiffOps } from './calendarNative.ts';
import { DiffOps, YearMonthDiffOps } from './calendarOps.ts';
import { DurationFields } from './durationFields.ts';
import { IntlCalendar } from './intlMath.ts';
import { IsoDateFields, IsoDateTimeFields, IsoTimeFields } from './isoFields.ts';
import { DiffOptions } from './optionsRefine.ts';
import { DurationSlots, InstantSlots, PlainDateSlots, PlainDateTimeSlots, PlainYearMonthSlots, ZonedDateTimeSlots, ZonedEpochSlots } from './slots.ts';
import { TimeZoneOps } from './timeZoneOps.ts';
import { DateUnitName, TimeUnitName, Unit, UnitName, YearMonthUnitName } from './units.ts';
import { NumberSign } from './utils.ts';
export declare function diffInstants(invert: boolean, instantSlots0: InstantSlots, instantSlots1: InstantSlots, options?: DiffOptions<TimeUnitName>): DurationSlots;
export declare function diffZonedDateTimes(getCalendarOps: (calendarId: string) => DiffOps, getTimeZoneOps: (timeZoneId: string) => TimeZoneOps, invert: boolean, slots0: ZonedDateTimeSlots, slots1: ZonedDateTimeSlots, options?: DiffOptions<UnitName>): DurationSlots;
export declare function diffPlainDateTimes(getCalendarOps: (calendarId: string) => DiffOps, invert: boolean, plainDateTimeSlots0: PlainDateTimeSlots, plainDateTimeSlots1: PlainDateTimeSlots, options?: DiffOptions<UnitName>): DurationSlots;
export declare function diffPlainDates(getCalendarOps: (calendarId: string) => DiffOps, invert: boolean, plainDateSlots0: PlainDateSlots, plainDateSlots1: PlainDateSlots, options?: DiffOptions<DateUnitName>): DurationSlots;
export declare function diffPlainYearMonth(getCalendarOps: (calendar: string) => YearMonthDiffOps, invert: boolean, plainYearMonthSlots0: PlainYearMonthSlots, plainYearMonthSlots1: PlainYearMonthSlots, options?: DiffOptions<YearMonthUnitName>): DurationSlots;
export declare function diffPlainTimes(invert: boolean, plainTimeSlots0: IsoTimeFields, plainTimeSlots1: IsoTimeFields, options?: DiffOptions<TimeUnitName>): DurationSlots;
export declare function diffZonedEpochsExact(timeZoneOps: TimeZoneOps, calendarOps: DiffOps, slots0: ZonedEpochSlots, slots1: ZonedEpochSlots, largestUnit: Unit, origOptions?: DiffOptions<UnitName>): DurationFields;
export declare function diffDateTimesExact(calendarOps: DiffOps, startIsoFields: IsoDateTimeFields, endIsoFields: IsoDateTimeFields, largestUnit: Unit, origOptions?: DiffOptions<UnitName>): DurationFields;
export declare function prepareZonedEpochDiff(timeZoneOps: TimeZoneOps, slots0: ZonedEpochSlots, slots1: ZonedEpochSlots, sign: NumberSign): [IsoDateFields, IsoDateFields, number];
export declare function prepareDateTimeDiff(startIsoDateTime: IsoDateTimeFields, endIsoDateTime: IsoDateTimeFields, sign: NumberSign): [IsoDateFields, IsoDateFields, number];
export declare function diffByDay(startIsoFields: IsoDateFields, endIsoFields: IsoDateFields): DurationFields;
export declare function diffDays(startIsoFields: IsoDateFields, endIsoFields: IsoDateFields): number;
export declare function diffEpochMilliByDay(epochMilli0: number, epochMilli1: number): number;
export declare function nativeDateUntil(this: NativeDiffOps, startIsoFields: IsoDateFields, endIsoFields: IsoDateFields, largestUnit: Unit): DurationFields;
export declare function computeIsoMonthsInYearSpan(yearDelta: number): number;
export declare function computeIntlMonthsInYearSpan(this: IntlCalendar, yearDelta: number, yearStart: number): number;
export declare function getCommonCalendarId(a: string, b: string): string;
export declare function getCommonTimeZoneId(a: string, b: string): string;
