import { DateParts, EraParts, MonthCodeParts, NativeCalendar, NativeDayOfYearOps, WeekParts, YearMonthParts } from './calendarNative.ts';
import { IsoDateFields, IsoDateTimeFields, IsoTimeFields } from './isoFields.ts';
import { Overflow } from './options.ts';
export declare const isoEpochOriginYear = 1970;
export declare const isoEpochFirstLeapYear = 1972;
export declare const isoMonthsInYear = 12;
export declare function computeIsoYear(isoFields: IsoDateFields): number;
export declare function computeIsoMonth(isoFields: IsoDateFields): number;
export declare function computeIsoDay(isoFields: IsoDateFields): number;
export declare function computeIsoDateParts(isoFields: IsoDateFields): DateParts;
export declare function computeIsoMonthCodeParts(_isoYear: number, isoMonth: number): MonthCodeParts;
export declare function computeIsoYearMonthForMonthDay(monthCodeNumber: number, isLeapMonth: boolean, _day: number): YearMonthParts | undefined;
export declare function computeIsoFieldsFromParts(year: number, month: number, day: number): IsoDateFields;
export declare function computeIsoDaysInWeek(_isoDateFields: IsoDateFields): number;
export declare function computeIsoMonthsInYear(_isoYear: number): number;
export declare function computeIsoDaysInMonth(isoYear: number, isoMonth: number): number;
export declare function computeIsoDaysInYear(isoYear: number): number;
export declare function computeIsoInLeapYear(isoYear: number): boolean;
export declare function computeIsoDayOfWeek(isoDateFields: IsoDateFields): number;
export declare function computeIsoWeekParts(this: NativeCalendar & NativeDayOfYearOps, isoDateFields: IsoDateFields): WeekParts;
export declare function computeIsoEraParts(this: NativeCalendar, isoFields: IsoDateFields): EraParts;
export declare function checkIsoDateTimeFields<P extends IsoDateTimeFields>(isoDateTimeFields: P): P;
export declare function checkIsoDateFields<P extends IsoDateFields>(isoInternals: P): P;
export declare function isIsoDateFieldsValid(isoFields: IsoDateFields): boolean;
export declare function constrainIsoTimeFields(isoTimeFields: IsoTimeFields, overflow?: Overflow): IsoTimeFields;
