import { BigNano } from './bigNano.ts';
import { DiffOps, MoveOps } from './calendarOps.ts';
import { DurationFields } from './durationFields.ts';
import { IsoDateFields, IsoDateTimeFields } from './isoFields.ts';
import { DateSlots, EpochAndZoneSlots, ZonedEpochSlots } from './slots.ts';
import { TimeZoneOps } from './timeZoneOps.ts';
import { Unit } from './units.ts';
export type RelativeToSlots = DateSlots | ZonedEpochSlots;
export type RelativeToSlotsNoCalendar = IsoDateFields | EpochAndZoneSlots;
export type Marker = IsoDateFields | IsoDateTimeFields | ZonedEpochSlots;
export type MarkerSystem<CO> = [Marker, CO, TimeZoneOps?];
export declare function createMarkerSystem<CO>(getCalendarOps: (calendarId: string) => CO, getTimeZoneOps: (timeZoneId: string) => TimeZoneOps, relativeToSlots: RelativeToSlots): MarkerSystem<CO>;
export type MarkerToEpochNano = (marker: Marker) => BigNano;
export type MoveMarker = (calendarOps: MoveOps, marker: Marker, durationFields: DurationFields) => Marker;
export type DiffMarkers = (calendarOps: DiffOps, marker0: Marker, marker1: Marker, largestUnit: Unit) => DurationFields;
export declare function createMarkerToEpochNano(timeZoneOps: TimeZoneOps | undefined): MarkerToEpochNano;
export declare function createMoveMarker(timeZoneOps: TimeZoneOps | undefined): MoveMarker;
export declare function createDiffMarkers(timeZoneOps: TimeZoneOps | undefined): DiffMarkers;
export declare function isZonedEpochSlots(marker: Marker | undefined): marker is ZonedEpochSlots;
export declare function isUniformUnit(unit: Unit, marker: Marker | undefined): boolean;
