import { NativeMoveOps, YearMonthParts } from './calendarNative.ts';
import { DayOps, MoveOps, YearMonthMoveOps } from './calendarOps.ts';
import { DurationFields } from './durationFields.ts';
import { IntlCalendar } from './intlMath.ts';
import { IsoDateFields, IsoDateTimeFields, IsoTimeFields } from './isoFields.ts';
import { Overflow } from './options.ts';
import { OverflowOptions } from './optionsRefine.ts';
import { DurationSlots, EpochSlots, InstantSlots, PlainDateSlots, PlainDateTimeSlots, PlainTimeSlots, PlainYearMonthSlots, ZonedDateTimeSlots, ZonedEpochSlots } from './slots.ts';
import { TimeZoneOps } from './timeZoneOps.ts';
export declare function moveInstant(doSubtract: boolean, instantSlots: InstantSlots, durationSlots: DurationSlots): InstantSlots;
export declare function moveZonedDateTime(getCalendarOps: (calendarId: string) => MoveOps, getTimeZoneOps: (timeZoneId: string) => TimeZoneOps, doSubtract: boolean, zonedDateTimeSlots: ZonedDateTimeSlots, durationSlots: DurationSlots, options?: OverflowOptions): ZonedDateTimeSlots;
export declare function movePlainDateTime(getCalendarOps: (calendarId: string) => MoveOps, doSubtract: boolean, plainDateTimeSlots: PlainDateTimeSlots, durationSlots: DurationSlots, options?: OverflowOptions): PlainDateTimeSlots;
export declare function movePlainDate(getCalendarOps: (calendarId: string) => MoveOps, doSubtract: boolean, plainDateSlots: PlainDateSlots, durationSlots: DurationSlots, options?: OverflowOptions): PlainDateSlots;
export declare function movePlainYearMonth(getCalendarOps: (calendar: string) => YearMonthMoveOps, doSubtract: boolean, plainYearMonthSlots: PlainYearMonthSlots, durationSlots: DurationSlots, options?: OverflowOptions): PlainYearMonthSlots;
export declare function movePlainTime(doSubtract: boolean, slots: PlainTimeSlots, durationSlots: DurationFields): PlainTimeSlots;
export declare function moveZonedEpochs(timeZoneOps: TimeZoneOps, calendarOps: MoveOps, slots: ZonedEpochSlots, durationFields: DurationFields, options?: OverflowOptions): EpochSlots;
export declare function moveDateTime(calendarOps: MoveOps, isoDateTimeFields: IsoDateTimeFields, durationFields: DurationFields, options?: OverflowOptions): IsoDateTimeFields;
export declare function moveDate(calendarOps: MoveOps, isoDateFields: IsoDateFields, durationFields: DurationFields, options?: OverflowOptions): IsoDateFields;
export declare function moveToDayOfMonthUnsafe<F extends IsoDateFields>(calendarOps: DayOps, isoFields: F, dayOfMonth?: number): F;
export declare function nativeDateAdd(this: NativeMoveOps, isoDateFields: IsoDateFields, durationFields: DurationFields, options?: OverflowOptions): IsoDateFields;
export declare function nativeYearMonthAdd(moveOps: NativeMoveOps, isoDateFields: IsoDateFields, years: number, months: number, overflow: Overflow): number;
export declare function isoMonthAdd(year: number, month: number, monthDelta: number): YearMonthParts;
export declare function intlMonthAdd(this: IntlCalendar, year: number, month: number, monthDelta: number): YearMonthParts;
export declare function moveByDays<F extends IsoDateFields>(isoFields: F, days: number): F & Partial<IsoTimeFields>;
