import type { DocEntry } from "../mcp-types.ts";

export const visualizationDocs: Record<string, DocEntry> = {
  graph: {
    name: "graph",
    category: "dataframe",
    signature: "graph(spec: GraphOptions<T>): TidyGraphWidget",
    description:
      "Create an interactive Vega-Lite visualization from the DataFrame. Supports scatter plots, line charts, bar charts, and area charts. The widget can be displayed in Jupyter notebooks, web applications, or saved as SVG/PNG. Automatically infers axis types (temporal for Date, quantitative for numbers, ordinal otherwise).",
    imports: ['import { createDataFrame } from "@tidy-ts/dataframe";'],
    parameters: [
      "spec: Graph specification object with:",
      "  - type: Chart type - 'scatter', 'line', 'bar', or 'area'",
      "  - mappings: Column mappings - { x, y, color?, series?, size?, shape? }",
      "    * x: Column name, accessor function, or array for X-axis (required)",
      "    * y: Column name, accessor function, or array for Y-axis (required)",
      "    * color: Optional column/accessor/array for color encoding (categorical or continuous)",
      "      - If not specified but series is provided, series is used for color",
      "    * series: Optional column/accessor/array for grouping multiple lines/bars/areas",
      "    * size: Optional column/accessor/array for point size encoding (scatter only, numeric)",
      "    * shape: Optional column/accessor/array for point shape encoding (scatter only, categorical)",
      "  - config: Optional styling configuration:",
      "    * layout: { title?, description?, width?: number | 'container', height?: number }",
      "      - width defaults to 'container' (fills parent), height defaults to 400",
      "    * xAxis/yAxis: { label?, domain?: [min, max]?, tickFormat?, hide? }",
      "      - domain filters data to only show points within range and enables clipping",
      "      - For Date axes, tickFormat defaults to '%b %Y'",
      "      - Non-quantitative x-axes get -45° label angle automatically",
      "    * grid: { show?: boolean (default: true), vertical?, horizontal? }",
      "    * color: { scheme?, colors?: string[] }",
      "      - schemes: 'default', 'blue', 'green', 'red', 'purple', 'orange', 'vibrant', 'professional', 'high_contrast'",
      "      - colors: Custom array of hex/rgb/hsl color strings",
      "    * legend: { show?: boolean (default: true when color/series used), position?, fontSize?, titleFontSize? }",
      "      - positions: 'top', 'bottom', 'left', 'right', 'top-left', 'top-right', 'bottom-left', 'bottom-right'",
      "      - fontSize defaults to 12, titleFontSize defaults to 13",
      "    * tooltip: { show?: boolean (default: true) }",
      "    * interactivity: { zoom?: boolean, pan?: boolean }",
      "      - Enables zoom/pan via interval selection bound to scales",
      "    * accessibility: { layer?: boolean } - Adds accessibility layer for screen readers",
      "    * animation: { duration?: number } - Animation duration in milliseconds",
      "    * scatter: { pointSize?: number (default: 60), pointOpacity?: number (default: 0.8) }",
      "    * line: { style?: 'monotone'|'linear'|'step'|'basis'|'cardinal' (default: 'linear'), dots?: boolean (default: false), strokeWidth?: number (default: 2), connectNulls?: boolean (default: false) }",
      "    * bar: { stacked?: boolean (default: false), radius?: number (default: 4) }",
      "    * area: { stacked?: boolean (default: false), style?: 'monotone'|'linear'|'step'|'basis'|'cardinal' (default: 'linear'), strokeWidth?: number (default: 1), opacity?: number (default: 0.7) }",
      "  - tooltip: Optional tooltip customization - { fields?: string[], format?: Record<string, (v: unknown) => string> }",
      "    - fields: Array of column names to show in tooltip (default: all columns)",
      "    - format: Custom formatter functions for specific fields",
    ],
    returns:
      "TidyGraphWidget with display() and save methods:\n  - savePNG({ filename, width?, height?, background?, scale? }): Promise<void>\n    - scale: Resolution multiplier 1-4 (default: 1, clamped to 1-4)\n  - saveSVG({ filename, width?, height?, background? }): Promise<void>\n    - width/height default to 700x400 if not specified in layout or save options",
    examples: [
      '// Scatter plot with color encoding\ndf.graph({\n  type: "scatter",\n  mappings: { x: "age", y: "income", color: "category" }\n})',
      '// Using accessor functions\nconst chart = df.graph({\n  type: "scatter",\n  mappings: {\n    x: (row) => row.age,\n    y: (row) => row.income * 1.1,\n    color: "category"\n  }\n})',
      '// Line chart with custom styling and domain filtering\ndf.graph({\n  type: "line",\n  mappings: { x: "date", y: "value", series: "category" },\n  config: {\n    layout: { title: "Sales Over Time", width: 800, height: 400 },\n    line: { style: "monotone", strokeWidth: 3, dots: true },\n    yAxis: { domain: [0, 1000], label: "Sales ($)" }\n  }\n})',
      '// Bar chart with stacking\nconst chart = df.graph({\n  type: "bar",\n  mappings: { x: "category", y: "count", series: "region" },\n  config: {\n    color: { scheme: "vibrant" },\n    bar: { stacked: true, radius: 8 }\n  }\n})',
      '// Area chart with custom tooltip fields\ndf.graph({\n  type: "area",\n  mappings: { x: "date", y: "value", series: "region" },\n  config: { area: { stacked: true, opacity: 0.7 } },\n  tooltip: { fields: ["date", "value", "region"] }\n})',
      '// Save as PNG with high resolution\nconst chart = df.graph({ type: "scatter", mappings: { x: "x", y: "y" } })\nawait chart.savePNG({ filename: "chart.png", width: 800, height: 600, scale: 2 })\nawait chart.saveSVG({ filename: "chart.svg", width: 800, height: 600 })',
      '// Scatter plot with multiple aesthetics and custom tooltip formatting\nsalesData\n  .mutate({\n    revenue: (r) => r.quantity * r.price,\n    profit: (r) => r.quantity * r.price * 0.2,\n  })\n  .graph({\n    type: "scatter",\n    mappings: {\n      x: "revenue",\n      y: "quantity",\n      color: "region",\n      size: "profit",\n    },\n    config: {\n      layout: { title: "Sales Analysis", width: 700, height: 400 },\n      scatter: { pointSize: 100, pointOpacity: 0.8 },\n      color: { scheme: "professional" },\n      legend: { show: true, position: "right" },\n      xAxis: { domain: [0, 5000], label: "Revenue ($)" },\n    },\n    tooltip: {\n      fields: ["revenue", "quantity", "region", "profit"],\n      format: { revenue: (v) => `$${Number(v).toFixed(2)}` }\n    }\n  })',
      '// Date axis with automatic temporal formatting\ndf.graph({\n  type: "line",\n  mappings: { x: "date", y: "value" },\n  config: {\n    layout: { title: "Time Series" },\n    // Date axis automatically gets "%b %Y" format\n  }\n})',
    ],
    related: ["mutate", "filter", "groupBy"],
    bestPractices: [
      "✓ GOOD: Use scatter plots for correlation analysis and multi-dimensional data",
      "✓ GOOD: Use line charts for trends and time series data",
      "✓ GOOD: Use bar charts for categorical comparisons",
      "✓ GOOD: Use area charts for cumulative data and part-to-whole relationships",
      "✓ GOOD: Chain with mutate() to create derived columns for visualization",
      "✓ GOOD: Use color schemes like 'professional' or 'vibrant' for better aesthetics",
      "✓ GOOD: Export charts as PNG/SVG for reports and presentations",
      "✓ GOOD: Use series mapping for multiple lines/bars/areas",
      "✓ GOOD: Configure tooltip.fields to show only relevant columns",
      "✓ GOOD: Use domain filtering to focus on specific data ranges",
      "✓ GOOD: Use scale: 2-4 for high-resolution PNG exports",
      "✓ GOOD: All row fields are automatically available in tooltips unless filtered",
      "✓ GOOD: Date columns are automatically detected and formatted as temporal axes",
      "Charts are interactive in Jupyter notebooks with hover tooltips",
      "Backed by Vega-Lite for high-quality visualizations",
      "When domain is specified, data is filtered and chart is clipped to that range",
    ],
    antiPatterns: [
      "❌ BAD: Using scatter plots for time series (use line charts instead)",
      "❌ BAD: Using bar charts for continuous numeric data (use line charts)",
      "❌ BAD: Not specifying mappings.x and mappings.y (required)",
      "❌ BAD: Using 'container' width in savePNG/saveSVG (use numeric width)",
      "❌ BAD: Using scale > 4 (will be clamped to 4)",
    ],
  },
};
