import { RawFormattable } from '../internal/intlFormatUtils.ts';
import { Instant } from './instant.ts';
import { PlainDate } from './plainDate.ts';
import { PlainDateTime } from './plainDateTime.ts';
import { PlainMonthDay } from './plainMonthDay.ts';
import { PlainTime } from './plainTime.ts';
import { PlainYearMonth } from './plainYearMonth.ts';
import { ZonedDateTime } from './zonedDateTime.ts';
export type TemporalFormattable = Instant | PlainDate | PlainDateTime | ZonedDateTime | PlainYearMonth | PlainMonthDay | PlainTime;
export type Formattable = TemporalFormattable | RawFormattable;
export type DateTimeFormat = Intl.DateTimeFormat;
export declare const DateTimeFormat: Intl.DateTimeFormatConstructor;
