export declare function wasm_dnorm(x: number, mean: number, sd: number, giveLog: boolean): number;
export declare function wasm_pnorm(x: number, mean: number, sd: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qnorm(p: number, mean: number, sd: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rnorm(mean: number, sd: number): number;
export declare function wasm_dbeta(x: number, shape1: number, shape2: number, giveLog: boolean): number;
export declare function wasm_pbeta(x: number, shape1: number, shape2: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qbeta(p: number, shape1: number, shape2: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rbeta(shape1: number, shape2: number): number;
export declare function wasm_dgamma(x: number, shape: number, rate: number, giveLog: boolean): number;
export declare function wasm_pgamma(x: number, shape: number, rate: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qgamma(p: number, shape: number, rate: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rgamma(shape: number, rate: number): number;
export declare function wasm_dchisq(x: number, df: number, giveLog: boolean): number;
export declare function wasm_pchisq(x: number, df: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qchisq(p: number, df: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rchisq(df: number): number;
export declare function wasm_df(x: number, df1: number, df2: number, giveLog: boolean): number;
export declare function wasm_pf(x: number, df1: number, df2: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qf(p: number, df1: number, df2: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rf(df1: number, df2: number): number;
export declare function wasm_dt(x: number, df: number, giveLog: boolean): number;
export declare function wasm_pt(x: number, df: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qt(p: number, df: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rt(df: number): number;
export declare function wasm_dexp(x: number, rate: number, giveLog: boolean): number;
export declare function wasm_pexp(x: number, rate: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qexp(p: number, rate: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rexp(rate: number): number;
export declare function wasm_dpois(x: number, lambda: number, giveLog: boolean): number;
export declare function wasm_ppois(x: number, lambda: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qpois(p: number, lambda: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rpois(lambda: number): number;
export declare function wasm_dbinom(x: number, size: number, prob: number, giveLog: boolean): number;
export declare function wasm_pbinom(x: number, size: number, prob: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qbinom(p: number, size: number, prob: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rbinom(size: number, prob: number): number;
export declare function wasm_dunif(x: number, min: number, max: number, giveLog: boolean): number;
export declare function wasm_punif(x: number, min: number, max: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qunif(p: number, min: number, max: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_runif(min: number, max: number): number;
export declare function wasm_dweibull(x: number, shape: number, scale: number, giveLog: boolean): number;
export declare function wasm_pweibull(x: number, shape: number, scale: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qweibull(p: number, shape: number, scale: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rweibull(shape: number, scale: number): number;
export declare function wasm_dgeom(x: number, prob: number, giveLog: boolean): number;
export declare function wasm_pgeom(x: number, prob: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qgeom(p: number, prob: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rgeom(prob: number): number;
export declare function wasm_dhyper(x: number, m: number, n: number, k: number, giveLog: boolean): number;
export declare function wasm_phyper(x: number, m: number, n: number, k: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qhyper(p: number, m: number, n: number, k: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rhyper(m: number, n: number, k: number): number;
export declare function wasm_dlnorm(x: number, meanlog: number, sdlog: number, giveLog: boolean): number;
export declare function wasm_plnorm(x: number, meanlog: number, sdlog: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qlnorm(p: number, meanlog: number, sdlog: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rlnorm(meanlog: number, sdlog: number): number;
export declare function wasm_dnbinom(x: number, r: number, p: number, giveLog: boolean): number;
export declare function wasm_pnbinom(x: number, r: number, p: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qnbinom(p: number, r: number, prob: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rnbinom(r: number, prob: number): number;
export declare function wasm_dwilcox(x: number, m: number, n: number, giveLog: boolean): number;
export declare function wasm_pwilcox(q: number, m: number, n: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qwilcox(p: number, m: number, n: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rwilcox(m: number, n: number): number;
export declare function wasm_dev1(x: number, location: number, scale: number, giveLog: boolean): number;
export declare function wasm_pev1(x: number, location: number, scale: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qev1(p: number, location: number, scale: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rev1(location: number, scale: number): number;
export declare function wasm_dzipf(x: number, n: number, s: number, giveLog: boolean): number;
export declare function wasm_pzipf(x: number, n: number, s: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qzipf(p: number, n: number, s: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rzipf(n: number, s: number): number;
export declare function wasm_ddirac(x: number, location: number, giveLog: boolean): number;
export declare function wasm_pdirac(x: number, location: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qdirac(p: number, location: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rdirac(location: number): number;
export declare function wasm_dpareto(x: number, scale: number, shape: number, giveLog: boolean): number;
export declare function wasm_ppareto(x: number, scale: number, shape: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_qpareto(p: number, scale: number, shape: number, lowerTail: boolean, giveLog: boolean): number;
export declare function wasm_rpareto(scale: number, shape: number): number;
