import type { AndersonDarlingTestResult, ChiSquareGoodnessOfFitTestResult, ChiSquareIndependenceTestResult, DAgostinoPearsonTestResult, DunnTestResult, FishersExactTestResult, GamesHowellTestResult, KendallCorrelationTestResult, KolmogorovSmirnovTestResult, KruskalWallisTestResult, MannWhitneyTestResult, OneSampleProportionTestResult, OneSampleTTestResult, OneSampleZTestResult, OneWayAnovaTestResult, PairedTTestResult, PearsonCorrelationTestResult, ShapiroWilkTestResult, SpearmanCorrelationTestResult, TukeyHsdTestResult, TwoSampleProportionTestResult, TwoSampleTTestResult, TwoSampleZTestResult, TwoWayAnovaTestResult, WelchAnovaTestResult, WilcoxonSignedRankTestResult } from "../stats/statistical-tests/types.ts";
export declare function anova_one_way_wasm(data: Float64Array, group_sizes: Uint32Array, alpha: number): OneWayAnovaTestResult;
export declare function welch_anova_wasm(data: Float64Array, group_sizes: Uint32Array, alpha: number): WelchAnovaTestResult;
export declare function anova_two_way_wasm(data: Float64Array, a_levels: number, b_levels: number, cell_sizes: Uint32Array, alpha: number): TwoWayAnovaTestResult;
export declare function anova_two_way_factor_a_wasm(data: Float64Array, a_levels: number, b_levels: number, cell_sizes: Uint32Array, alpha: number): OneWayAnovaTestResult;
export declare function anova_two_way_factor_b_wasm(data: Float64Array, a_levels: number, b_levels: number, cell_sizes: Uint32Array, alpha: number): OneWayAnovaTestResult;
export declare function anova_two_way_interaction_wasm(data: Float64Array, a_levels: number, b_levels: number, cell_sizes: Uint32Array, alpha: number): OneWayAnovaTestResult;
export declare function chi_square_independence(observed: Float64Array, n_rows: number, n_cols: number, alpha: number): ChiSquareIndependenceTestResult;
export declare function chi_square_goodness_of_fit(observed: Float64Array, expected: Float64Array, alpha: number): ChiSquareGoodnessOfFitTestResult;
export declare function t_test_one_sample(x: Float64Array, mu: number, alpha: number, alternative: string): OneSampleTTestResult;
export declare function t_test_two_sample_independent(x: Float64Array, y: Float64Array, alpha: number, alternative: string, pooled: boolean): TwoSampleTTestResult;
export declare function t_test_paired(x: Float64Array, y: Float64Array, alpha: number, alternative: string): PairedTTestResult;
export declare function z_test_one_sample(x: Float64Array, mu: number, sigma: number, alpha: number, alternative: string): OneSampleZTestResult;
export declare function z_test_two_sample(x: Float64Array, y: Float64Array, sigma_x: number, sigma_y: number, alpha: number, alternative: string): TwoSampleZTestResult;
export declare function proportion_test_one_sample(x: number, n: number, p0: number, alpha: number, alternative: string): OneSampleProportionTestResult;
export declare function proportion_test_two_sample(x1: number, n1: number, x2: number, n2: number, alpha: number, alternative: string, pooled: boolean): TwoSampleProportionTestResult;
export declare function mann_whitney_test_with_config(x: Float64Array, y: Float64Array, exact: boolean, continuity_correction: boolean, alpha: number, alternative: string): MannWhitneyTestResult;
export declare function wilcoxon_w_test(x: Float64Array, y: Float64Array, alpha: number, alternative: string): WilcoxonSignedRankTestResult;
export declare function shapiro_wilk_test(x: Float64Array, alpha: number): ShapiroWilkTestResult;
export declare function anderson_darling_test(x: Float64Array, alpha: number): AndersonDarlingTestResult;
export declare function dagostino_pearson_test(x: Float64Array, alpha: number): DAgostinoPearsonTestResult;
export declare function fishers_exact_test_wasm(a: number, b: number, c: number, d: number, alternative: string, odds_ratio: number, alpha: number): FishersExactTestResult;
export declare function kruskal_wallis_test_wasm(data: Float64Array, group_sizes: Uint32Array, alpha: number): KruskalWallisTestResult;
export declare function pearson_correlation_test(x: Float64Array, y: Float64Array, alternative: string, alpha: number): PearsonCorrelationTestResult;
export declare function spearman_correlation_test(x: Float64Array, y: Float64Array, alternative: string, alpha: number): SpearmanCorrelationTestResult;
export declare function kendall_correlation_test(x: Float64Array, y: Float64Array, alternative: string, alpha: number, exact?: boolean): KendallCorrelationTestResult;
export declare function levene_test_wasm(data: Float64Array, group_sizes: Uint32Array, alpha: number): OneWayAnovaTestResult;
export declare function tukey_hsd_wasm(data: Float64Array, group_sizes: Uint32Array, alpha: number): TukeyHsdTestResult;
export declare function games_howell_wasm(data: Float64Array, group_sizes: Uint32Array, alpha: number): GamesHowellTestResult;
export declare function dunn_test_wasm(data: Float64Array, group_sizes: Uint32Array, alpha: number): DunnTestResult;
export declare function kolmogorov_smirnov_test_wasm(x: Float64Array, y: Float64Array, alternative: string, alpha: number): KolmogorovSmirnovTestResult;
export declare function kolmogorov_smirnov_uniform_wasm(x: Float64Array, min: number, max: number, alternative: string, alpha: number): KolmogorovSmirnovTestResult;
