export declare function unique_f64(values: Float64Array): Float64Array;
export declare function n_unique_f64(values: Float64Array): number;
export declare function unique_i32(values: Int32Array): Int32Array;
export declare function unique_str(values: string[]): string[];
export declare function count_f64(values: Float64Array, target: number): number;
export declare function count_i32(values: Int32Array, target: number): number;
export declare function count_str(values: string[], target: string): number;
export declare function mean_wasm(values: Float64Array): number;
export declare function sum_wasm(values: Float64Array): number;
export declare function quantile_wasm(values: Float64Array, probs: Float64Array): Float64Array;
export declare function median_wasm(values: Float64Array): number;
export declare function iqr_wasm(values: Float64Array): number;
export declare function variance_wasm(values: Float64Array): number;
export declare function stdev_wasm(values: Float64Array): number;
export declare function distinct_rows_generic_typed(column_data: Uint32Array[], view_index: Uint32Array): Uint32Array;
