name: Build CI Docker Image

on:
  push:
    branches: [main]
    paths:
      - '.github/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .github
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tidy-ts-ci:latest
            ghcr.io/${{ github.repository_owner }}/tidy-ts-ci:${{ github.sha }}
