name: Update Coverage Badge

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.4.2
          cache: true

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('jsonlite', 'nortest', 'moments', 'fBasics'), repos='https://cran.r-project.org/')"

      - name: Create output directories
        run: |
          mkdir -p examples/dataframe/output

      - name: Run tests with coverage
        run: deno test -A --coverage=cov_profile --parallel src/dataframe examples/dataframe tests/glm tests/statistical_tests

      - name: Generate coverage report
        run: deno coverage cov_profile --detailed > coverage.txt

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(grep -o '[0-9]*\.[0-9]*%' coverage.txt | head -1 | sed 's/%//')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Coverage: $COVERAGE%"

      - name: Update README with coverage badge
        run: |
          # Create the new badge URL
          COVERAGE="${{ steps.coverage.outputs.coverage }}"
          BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen"

          # Update the README.md file
          sed -i "s|https://img.shields.io/badge/coverage-[0-9]*\.[0-9]*%25-brightgreen|${BADGE_URL}|g" README.md

          # Check if changes were made
          if git diff --quiet README.md; then
            echo "No changes to README.md"
          else
            echo "README.md updated with new coverage: ${COVERAGE}%"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "Update coverage badge to ${COVERAGE}%"
            git push
          fi
